### ISSUE TITLE
Excluding modules

### ISSUE THREAD

**Issue by nathanmesserbbc** [scalableminds/amd-optimize#22]
We have a need to sometimes exclude dependencies from the optimised js file we produce, as they're already available in the page the file will go into.

I know the docs say that options.exclude isn't implemented, but I also noticed that there's a commit adding added deep and shallow exclusion.

Is it possible to have a dependency that isn't processed by amd-optimize, and so can be pulled in from the page the optimized js file is loaded into?

**Comment by develar** [comment]
The problem — amd-optimize in any case tries to resolve excluded modules.

Workaround:
specify loader:               loader: amdOptimize.loader(function (moduleName) {
                return "lib/empty.js"
              })


and create empty file "empty.js": {}
