### ISSUE TITLE
Include example using bower

### ISSUE THREAD

**Issue by beatgammit** [scalableminds/amd-optimize#23]
I haven't been able to figure out how to use bower in a requirejs project using gulp as the builder. I have the following structure:
- src/
  - main.js
  - require.config.js - generated with bower-requirejs
- bower_components/
  - reqwest

Here's my `gulpfile.js`:

```
var gulp = require('gulp'),
    concat = require('gulp-concat'),
    amdOptimize = require('amd-optimize'),
    bowerRequireJS = require('bower-requirejs');

gulp.task('default', function () {
    gulp.src(['src/main.js', 'bower_components/**/*.js'])
        .pipe(amdOptimize('main', {baseURL: 'src', configFile: 'src/require.config.js'}))
        .pipe(concat('main.js'))
        .pipe(gulp.dest('public'));
});

gulp.task('bower', function () {
    var options = {
        baseUrl: 'src',
        config: 'src/require.config.js',
        transitive: true,
    };

    bowerRequireJS(options, function (rjsConfigFromBower) {
        console.log('whatever');
    });
});
```

And here's my `require.config.js` generated from the 'bower' task:

```
require.config({
  shim: {

  },
  paths: {
    coordinator: "../bower_components/coordinator/coordinator",
    reqwest: "../bower_components/reqwest/reqwest"
  },
  packages: [

  ]
});
```

I've tried several different things and I've gotten the same error each time:

> No file for module 'request' found

I feel that this is a pretty common problem and it would be fantastic to get an example that works. I have the same behavior working with `Grunt`, but I'd like to switch to `gulp`.

Is this something that _should_ work with `amd-optimize`, or am I barking up the wrong tree?

**Comment by shangyue1110** [comment]
I have an js file in another directory, but my project need to import this file, structure is following:
-webapp
       require.config.js
       static/modules/myModule/
                                                 moduleEntry.js
                                                 dependencyA.js
                                                 dependencyB.js
                                                 ......
      static/app/extend/widgetsDefine.js

and  gulp script is like this:

`gulp.task('build', function () {
    gulp.src([
            'static/app/extend/widgetsDefine.js',
            'static/modules/myModule/*.js',
            '!static/modules/myModule/*.min.js'],{base:'static/modules/myModule/'})
        .pipe(amdOptimize("static/modules/myModule/moduleEntry", {
            baseUrl:'static/modules/myModule/',
            configFile:'main.js',
            exclude:[
                'static/modules/otherModules/moduleC',
                'static/app/extend/widgetsDefine.js'
            ],
            findNestedDependencies:false
        }))
        .pipe(concat("moduleEntry-concat.js"))
        .pipe(gulp.dest("static/modules/myModule"))
        .pipe(rename("moduleEntry-concat.min.js"))
        .pipe(uglify())
        .pipe(gulp.dest("static/modules/myModule"));
});`

then amd-optimize catch an error:
Error: No file for module 'static/modules/myModule/moduleEntry' found.

so , How can I import a js file form a different directory?

waiting for answer sincerely
