### ISSUE TITLE
options.paths

### ISSUE THREAD

**Issue by qingxiao** [scalableminds/amd-optimize#30]
requirejs.config can be like this:
```
baseUrl:"js/lib", 
paths: {
                page: '../page'
            }
```
use module  js/page/frame.js :
```
require(['page/frame']);
```
but in the amd-optiomize options.paths like that it can't run 
```
Error: No file for module 'page/frame' found.
```

so , them can't user same config ? or I use it error way?

**Comment by normanrz** [comment]
should've been fixed with #33 (0.4.2 on npm). maybe @qingxiao can confirm?
